#!/usr/bin/env python3

from setuptools import setup

from apt_method_azure import __version__

setup(
	name = 'apt-method-azure',
	version = __version__,
	packages = [ 'apt_method_azure' ],
	entry_points = {
		'distutils.commands': [
			'deb = commands.deb:deb',
			'clear = commands.clear:clear'
		]
	}
)
